name: confeitaria
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.8.0
  http: ^1.2.2
  flutter_custom_tabs: ^2.1.0
  intl_phone_field: ^3.2.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0
  
flutter:

  uses-material-design: true

  assets:
    - imagens/logo-confeitaria.png
    - imagens/bolo_chocolate.jpg
    - imagens/brigadeiros.jpg
    - imagens/hortela.jpeg